# Generated by Django 4.2.7 on 2025-08-23 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('tutorial', 'Tutorial'), ('article', 'Article'), ('video', 'Video'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('course_id', models.CharField(max_length=20)),
                ('recommendation_priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('estimated_duration', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recommendation_priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('performance_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('completed_courses', models.TextField(default='[]')),
                ('pending_courses', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='recommended', max_length=20)),
                ('confidence_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason', models.TextField(blank=True)),
                ('ai_metadata', models.TextField(default='{}')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webq_app.learningresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webq_app.student')),
            ],
            options={
                'ordering': ['-recommendation_date'],
                'unique_together': {('student', 'resource')},
            },
        ),
    ]
